DWAPlannerROS: 
  acc_lim_theta: 3.2
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_limit_trans: 0.1
  angular_sim_granularity: 0.1
  forward_point_distance: 0.325
  goal_distance_bias: 9.0
  #holonomic_robot: false
  #latch_xy_goal_tolerance: true
  max_rot_vel: 1.0
  max_scaling_factor: 0.2
  max_trans_vel: 0.55
  max_vel_x: 0.55
  max_vel_y: 0.0
  min_rot_vel: 0.2
  min_trans_vel: 0.0
  min_vel_x: 0.0
  min_vel_y: 0.0
  occdist_scale: 0.01
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 5.0
  prune_plan: true
  restore_defaults: false
  rot_stopped_vel: 0.1
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 1.7
  stop_time_buffer: 0.2
  trans_stopped_vel: 0.0
  use_dwa: true
  vth_samples: 20
  vx_samples: 3
  vy_samples: 10
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.1